name: Deploy MSRC gui for Linux

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - msrc_gui/**

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Get actions code
        uses: actions/checkout@v4
        
      - name: Install QT
        uses: jurplel/install-qt-action@v2
        
      - name: Build
        run: |
          mkdir build
          cd build
          qmake ../msrc_gui
          make
          
      - name: Install LinuxDeploy
        run: |
          cd msrc_gui
          wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
          sudo chmod +x linuxdeployqt-continuous-x86_64.AppImage
      
      - name: Install fuse
        run: sudo apt install libfuse2

      - name: Create AppImage
        run: |
          cp build/msrc_gui msrc_gui/appdir
          cd msrc_gui/appdir
          ../linuxdeployqt-continuous-x86_64.AppImage msrc_gui -appimage
          mv *.AppImage msrc_gui.AppImage

      - name: Upload to Google Drive
        uses: logickoder/g-drive-upload@main
        with:
          credentials: ${{ secrets.GOOGLE_ID }}
          filename: 'msrc_gui/appdir/msrc_gui.AppImage'
          folderId: ${{ secrets.FOLDER_ID }}
          overwrite: 'true'
          name: msrc_gui_smart_esc.AppImage
